"""Small, repeatable agent composition; definitions are ordinary trusted Python."""
from __future__ import annotations

import argparse
import json
import logging
import math
import os
from pathlib import Path
from pprint import pformat
import runpy
import signal
import tempfile
import threading
from time import monotonic
from dataclasses import dataclass, field

from theseus.agentic_memory import AgenticMemory
from theseus.auto_core import Autocore
from theseus.cadence import Cadence
from theseus.chat_observer import TerminalChatObserver
from theseus.context_assembler import ContextAssembler
from theseus.durable_delivery import DeliveryJournal, DurableInbox, DurableOutbox
from theseus.memory_module import MemoryModule
from theseus.memory_consolidator import MemoryConsolidator
from theseus.memory_store import MemoryStore
from theseus.model_providers import PROVIDER_REGISTRY
from theseus.ooda_core import OODACore
from theseus.stimulus_log import PairedStimulusLog, StimulusLog
from theseus.telegram_api import TelegramBotAPI, TelegramSender
from theseus.telegram_observer import TELEGRAM_TRANSPORT, TelegramObserver
from theseus.tools.recall import RecallTool
from theseus.tools.registry import all_tools
from theseus.tools.terminal_chat import TerminalChat
from theseus.tools.telegram import TelegramTool
from theseus.tools.web_chat import WebChat
from theseus.web_chat_ui_observer import WebChatUIObserver

GENERATED_HEADER = "# Generated by Theseus Agent Assembler. Edit the definition and reassemble.\n"


@dataclass(frozen=True)
class ModelSpec:
    provider: str
    model: str
    context: int = 4096
    tick: int = 300
    during: str | None = None


@dataclass(frozen=True)
class MemorySpec:
    # Autocore holds either module; consolidation remains an explicit agent policy.
    kind: str = "none"
    model: ModelSpec | None = None
    embedding: ModelSpec | None = None
    recall_budget_tokens: int = 2000
    recall_description: str | None = None
    consolidate_every_seconds: float | None = None
    episode_max_events: int = 20
    episode_max_chars: int = 24000
    episode_context_events: int = 2


@dataclass(frozen=True)
class InterfaceSpec:
    kind: str = "terminal"
    host: str = "127.0.0.1"
    port: int = 8000
    bot_token_env: str = "TELEGRAM_BOT_TOKEN"
    allowed_user_ids: tuple[int, ...] = ()
    allowed_chat_ids: tuple[int, ...] = ()
    poll_timeout_seconds: int = 25
    outgoing_interval_seconds: float = 0.0
    outgoing_chat_ids_only: bool = False


@dataclass(frozen=True)
class PairingSpec:
    peer_log_path: str
    peer_name: str
    peer_context_fraction: float = 0.25


@dataclass(frozen=True)
class AgentSpec:
    name: str
    constitution: str
    models: tuple[ModelSpec, ...]
    persona: str = ""
    core: str = "auto"
    tools: tuple[str, ...] = ()
    memory: MemorySpec = field(default_factory=MemorySpec)
    interface: InterfaceSpec = field(default_factory=InterfaceSpec)
    window_size: int = 200
    pairing: PairingSpec | None = None

    def validate(self) -> None:
        for label, value in (("name", self.name), ("constitution", self.constitution)):
            if not isinstance(value, str) or not value.strip():
                raise ValueError(f"{label} must be nonempty text")
        if not isinstance(self.persona, str):
            raise ValueError("persona must be text")
        if self.core not in ("auto", "ooda"):
            raise ValueError("core must be 'auto' or 'ooda'")
        if type(self.window_size) is not int or self.window_size <= 0:
            raise ValueError("window_size must be a positive integer")
        if self.pairing is not None:
            pair = self.pairing
            if not isinstance(pair, PairingSpec):
                raise ValueError("pairing must be a PairingSpec")
            if not isinstance(pair.peer_log_path, str) or not pair.peer_log_path.strip():
                raise ValueError("pairing peer_log_path must be nonempty text")
            if not isinstance(pair.peer_name, str) or not pair.peer_name.strip():
                raise ValueError("pairing peer_name must be nonempty text")
            if not isinstance(pair.peer_context_fraction, (int, float)) or not 0 < pair.peer_context_fraction < 1:
                raise ValueError("pairing peer_context_fraction must be between 0 and 1")
        if not isinstance(self.models, tuple) or not self.models:
            raise ValueError("models must be a nonempty tuple of ModelSpec values")
        for model in self.models:
            _validate_model(model)
        if self.core == "auto":
            if sum(model.during is None for model in self.models) != 1:
                raise ValueError("auto requires exactly one default model (during=None)")
            cadence = Cadence.parse(self.cadence_text())
            if cadence.lint_lines() or len(cadence.rules) != len(self.models):
                raise ValueError(f"Invalid cadence: {self.cadence_text()}")
        elif any(model.during is not None for model in self.models):
            raise ValueError("OODA models are ordered fallbacks; during is only for auto")
        elif len({model.context for model in self.models}) != 1:
            raise ValueError("OODA fallback models must use the same context budget")
        if not isinstance(self.tools, tuple) or any(not isinstance(t, str) for t in self.tools):
            raise ValueError("tools must be a tuple of registered tool names")
        unknown = set(self.tools) - all_tools().keys()
        if unknown:
            raise ValueError(f"Unknown tools: {', '.join(sorted(unknown))}")
        if len(set(self.tools)) != len(self.tools):
            raise ValueError("Duplicate tool names")
        if not isinstance(self.interface, InterfaceSpec):
            raise ValueError("interface must be an InterfaceSpec")
        if self.interface.kind not in ("terminal", "web", "telegram", "none"):
            raise ValueError("interface must be 'terminal', 'web', 'telegram', or 'none'")
        if self.interface.kind == "none" and self.core != "auto":
            raise ValueError("The headless interface requires auto")
        if not isinstance(self.interface.host, str) or not self.interface.host.strip():
            raise ValueError("interface host must be nonempty text")
        if type(self.interface.port) is not int or not 1 <= self.interface.port <= 65535:
            raise ValueError("interface port must be between 1 and 65535")
        if not isinstance(self.interface.bot_token_env, str) or not self.interface.bot_token_env.strip():
            raise ValueError("interface bot_token_env must be nonempty text")
        for label, values in (
            ("allowed_user_ids", self.interface.allowed_user_ids),
            ("allowed_chat_ids", self.interface.allowed_chat_ids),
        ):
            if not isinstance(values, tuple) or any(
                isinstance(value, bool) or not isinstance(value, int) for value in values
            ):
                raise ValueError(f"interface {label} must be a tuple of integer IDs")
            if len(set(values)) != len(values):
                raise ValueError(f"interface {label} contains duplicate IDs")
        if (
            self.interface.kind == "telegram"
            and not self.interface.allowed_user_ids
            and not self.interface.allowed_chat_ids
        ):
            raise ValueError("Telegram requires at least one allowed user or chat ID")
        if (
            type(self.interface.poll_timeout_seconds) is not int
            or not 1 <= self.interface.poll_timeout_seconds <= 50
        ):
            raise ValueError("interface poll_timeout_seconds must be between 1 and 50")
        if not isinstance(self.interface.outgoing_interval_seconds, (int, float)) or self.interface.outgoing_interval_seconds < 0:
            raise ValueError("interface outgoing_interval_seconds must be nonnegative")
        if not isinstance(self.interface.outgoing_chat_ids_only, bool):
            raise ValueError("interface outgoing_chat_ids_only must be a boolean")
        if self.interface.outgoing_chat_ids_only and not self.interface.allowed_chat_ids:
            raise ValueError("outgoing_chat_ids_only requires allowed_chat_ids")
        if not isinstance(self.memory, MemorySpec):
            raise ValueError("memory must be a MemorySpec")
        memory = self.memory
        if memory.consolidate_every_seconds is not None:
            if (memory.kind != "module" or memory.model is None
                or not isinstance(memory.consolidate_every_seconds, (int, float))
                or not math.isfinite(memory.consolidate_every_seconds)
                or memory.consolidate_every_seconds <= 0):
                raise ValueError("scheduled consolidation requires module memory, an extraction model, and a positive interval")
        if type(memory.episode_max_events) is not int or memory.episode_max_events < 1:
            raise ValueError("episode_max_events must be positive")
        if type(memory.episode_max_chars) is not int or memory.episode_max_chars < 4096:
            raise ValueError("episode_max_chars must be at least 4096")
        if type(memory.episode_context_events) is not int or memory.episode_context_events < 0:
            raise ValueError("episode_context_events must be a nonnegative integer")
        if memory.kind not in ("none", "amem", "module"):
            raise ValueError("memory kind must be 'none', 'amem', or 'module'")
        if type(memory.recall_budget_tokens) is not int or memory.recall_budget_tokens <= 0:
            raise ValueError("recall_budget_tokens must be a positive integer")
        if memory.recall_description is not None and not isinstance(memory.recall_description, str):
            raise ValueError("recall_description must be text")
        if memory.kind == "amem":
            _validate_model(memory.model)
            _validate_model(memory.embedding)
        elif memory.kind == "module":
            if self.core != "auto":
                raise ValueError("MemoryModule requires auto; it does not implement OODA's form() lifecycle")
            for model in (memory.model, memory.embedding):
                if model is not None:
                    _validate_model(model)
        elif any(value is not None for value in (
            memory.model, memory.embedding, memory.recall_description
        )):
            raise ValueError("memory kind 'none' does not accept memory options")

    def cadence_text(self) -> str:
        return "# Cadence\n\n" + "".join(
            f"- {model.during or 'default'}: {model.provider} {model.model}, "
            f"context {model.context}, tick every {model.tick} seconds\n"
            for model in self.models
        )


def _validate_model(model: ModelSpec | None) -> None:
    if not isinstance(model, ModelSpec):
        raise ValueError("Expected a ModelSpec")
    if model.provider not in PROVIDER_REGISTRY:
        raise ValueError(f"Unknown provider {model.provider!r}; choose from {', '.join(PROVIDER_REGISTRY)}")
    if not isinstance(model.model, str) or not model.model or any(c.isspace() for c in model.model):
        raise ValueError("Model name must be a nonempty token without whitespace")
    for label, value in (("context", model.context), ("tick", model.tick)):
        if type(value) is not int or value <= 0:
            raise ValueError(f"Model {label} must be a positive integer")
    if model.during is not None and (not isinstance(model.during, str) or not model.during):
        raise ValueError("during must be a time window such as '08:00-22:00'")


def _provider(spec: ModelSpec):
    return PROVIDER_REGISTRY[spec.provider](model=spec.model)


@dataclass
class AssembledAgent:
    core: Autocore | OODACore
    observer: TerminalChatObserver | WebChatUIObserver | TelegramObserver | None
    spec: AgentSpec
    _shutdown_requested: threading.Event = field(
        default_factory=threading.Event, init=False, repr=False
    )
    _shutdown_started_at: float | None = field(default=None, init=False, repr=False)

    def run(self) -> None:
        if self.spec.interface.kind == "none":
            self.core.loop()
            return
        if self.spec.interface.kind == "telegram" and self.spec.core == "auto":
            # Recover before Autocore's immediate first turn. Otherwise that turn can see
            # the already-persisted stimulus and then inbox recovery wakes a redundant
            # second turn for the same message.
            if self.observer.outbox is not None:
                self.observer.outbox.recover()
            self.observer.recover_pending()
        if self.spec.core == "auto":
            threading.Thread(target=self.core.loop, name="agent-core", daemon=True).start()
        if self.spec.interface.kind == "web":
            self.observer.serve(host=self.spec.interface.host, port=self.spec.interface.port)
        elif self.spec.interface.kind == "telegram":
            self.observer.run()
        else:
            while True:
                try:
                    self.observer.observe_chat_message()
                except EOFError:
                    break

    def request_shutdown(self) -> None:
        """Signal every managed component; never block or perform cleanup here."""
        # Python signal handlers run on the main thread and may interrupt ordinary
        # code, so this path intentionally takes no locks and performs no I/O.
        if self._shutdown_started_at is None:
            self._shutdown_started_at = monotonic()
        self._shutdown_requested.set()
        request = getattr(self.core, "request_shutdown", None)
        if request is not None:
            request()
        if self.observer is not None:
            stop = getattr(self.observer, "stop", None)
            if stop is not None:
                stop()

    def preflight(self) -> dict[str, object]:
        """Validate local recoverability without polling, dispatch, or model calls."""
        self.spec.validate()
        events = self.core.stimulus_log.read_all()
        if self.observer is not None and hasattr(self.observer, "inbox"):
            self.observer.inbox.journal.preflight()
        memory = self.core.memory
        if isinstance(memory, AgenticMemory):
            memory.store.read_all()
        elif isinstance(memory, MemoryModule):
            # Construction performs deterministic pending-transaction recovery. Reading
            # the layers here forces malformed persisted records to surface as not ready.
            memory.knowledge.read_all()
            memory.wisdom.read_all()
        return {
            "name": self.spec.name,
            "events": len(events),
            "ready": True,
        }

    def run_managed(
        self,
        *,
        deployment_id: str,
        agent_id: str,
        control_path: Path,
        status_path: Path,
        shutdown_timeout_seconds: float = 30.0,
    ) -> bool:
        """Run owned workers and acknowledge only a complete bounded drain."""
        from theseus.deployment_control import ActivationStore, LifecycleStatusStore

        if self.spec.core != "auto" or self.spec.interface.kind not in ("telegram", "none"):
            raise ValueError("managed lifecycle supports only Auto Telegram/headless agents")
        if (
            isinstance(shutdown_timeout_seconds, bool)
            or not isinstance(shutdown_timeout_seconds, (int, float))
            or shutdown_timeout_seconds <= 0
        ):
            raise ValueError("shutdown timeout must be positive")
        control_path = Path(control_path)
        activation = ActivationStore(control_path.parent, deployment_id)
        if activation.path != control_path:
            raise ValueError(f"activation path must be {activation.path}")
        activation.require_active()
        self.preflight()
        lifecycle = LifecycleStatusStore(status_path, agent_id)
        running = lifecycle.running()
        failures: list[str] = []
        threads: list[threading.Thread] = []

        if self.spec.interface.kind == "telegram":
            if self.observer.outbox is not None:
                self.observer.outbox.recover()
            self.observer.recover_pending()

        def start_worker(name: str, target) -> None:
            def owned() -> None:
                try:
                    target()
                except BaseException as exc:
                    failures.append(f"{name}: {type(exc).__name__}: {exc}")
                finally:
                    if not self._shutdown_requested.is_set():
                        failures.append(f"{name} exited before shutdown")
                        self.request_shutdown()

            thread = threading.Thread(target=owned, name=name, daemon=True)
            threads.append(thread)
            thread.start()

        start_worker("agent-core", self.core.loop)
        if self.observer is not None:
            start_worker("agent-observer", self.observer.run)

        self._shutdown_requested.wait()
        started = self._shutdown_started_at or monotonic()
        deadline = started + float(shutdown_timeout_seconds)
        for thread in threads:
            thread.join(max(0.0, deadline - monotonic()))
        alive = [thread.name for thread in threads if thread.is_alive()]
        tools = list({id(tool): tool for tool in self.core.tools.values()}.values())
        child_tools = [
            tool for tool in tools
            if callable(getattr(tool, "has_live_children", None)) and tool.has_live_children()
        ]
        clean = not alive and not failures and not child_tools
        detail_parts = failures + ([f"threads still alive: {', '.join(alive)}"] if alive else [])
        if child_tools:
            detail_parts.append("managed tool child processes remained after the deadline")
        if clean:
            self._close_resources()
        else:
            for tool in child_tools:
                terminate = getattr(tool, "terminate_children", None)
                if terminate is not None:
                    terminate()
        lifecycle.stopped(
            running.run_id,
            clean=clean,
            detail="; ".join(detail_parts) or None,
        )
        return clean

    def _close_resources(self) -> None:
        seen: set[int] = set()
        providers = getattr(self.core, "model_providers", {})
        resources = list(providers.values() if isinstance(providers, dict) else providers)
        memory = self.core.memory
        if memory is not None:
            resources.extend(getattr(memory, "model_providers", getattr(memory, "_model_providers", ())))
            resources.extend(getattr(memory, "embedding_providers", getattr(memory, "_embedding_providers", ())))
        resources.extend(self.core.tools.values())
        if self.observer is not None:
            api = getattr(self.observer, "api", None)
            if api is not None:
                resources.append(api)
            outbox = getattr(self.observer, "outbox", None)
            sender = getattr(outbox, "sender", None)
            if sender is not None:
                resources.append(sender)
                sender_api = getattr(sender, "api", None)
                if sender_api is not None:
                    resources.append(sender_api)
        for resource in resources:
            if id(resource) in seen:
                continue
            seen.add(id(resource))
            close = getattr(resource, "close", None)
            if callable(close):
                close()


def build_agent(
    spec: AgentSpec, home: Path, log_path: Path | None = None
) -> AssembledAgent:
    """Compose without starting loops, listeners, or making model requests.

    Identity and cadence are assembler-owned and reapplied on boot. Everything
    else in home is runtime-owned. Use a fresh home for an isolated test agent.
    """
    spec.validate()
    home = Path(home).resolve()
    if log_path is None:
        resolved_log_path = home / "stimulus_log.jsonl"
    else:
        resolved_log_path = Path(log_path).resolve()
        legacy_log = home / "stimulus_log.jsonl"
        if legacy_log.exists() and legacy_log.stat().st_size:
            raise ValueError(
                "home already contains a stimulus log; use import_stopped_home "
                "before selecting an external log path"
            )
    # Construct OODA providers before touching the home (e.g. missing API keys).
    providers = [_provider(model) for model in spec.models] if spec.core == "ooda" else []
    home.mkdir(parents=True, exist_ok=True)
    for name, content in (("CONSTITUTION.md", spec.constitution),
                          ("PERSONA.md", spec.persona),
                          ("CADENCE.md", spec.cadence_text())):
        _atomic_write(home / name, content)
    tools = {name: tool for name, tool in all_tools(cwd=home).items() if name in spec.tools}
    if spec.pairing is not None:
        peer_path = Path(spec.pairing.peer_log_path)
        if not peer_path.is_absolute():
            peer_path = home / peer_path
        log = PairedStimulusLog(
            resolved_log_path, peer_path, peer_name=spec.pairing.peer_name,
            peer_context_fraction=spec.pairing.peer_context_fraction,
        )
    else:
        log = StimulusLog(resolved_log_path)
    if spec.core == "auto":
        core = Autocore(name=spec.name, home_directory=home, tools=tools, stimulus_log=log)
        core.context_assembler.window_size = spec.window_size
    else:
        core = OODACore(
            name=spec.name, constitution=spec.constitution, persona=spec.persona,
            stimulus_log=log, tools=tools, model_providers=providers,
            context_assembler=ContextAssembler(
                log, window_size=spec.window_size, context_tokens=spec.models[0].context,
            ),
        )
    if spec.memory.kind == "amem":
        core.memory = AgenticMemory(
            model_providers=[_provider(spec.memory.model)],
            embedding_providers=[_provider(spec.memory.embedding)],
            store=MemoryStore(home / "a_mem.jsonl"), stimulus_log=core.stimulus_log,
        )
    elif spec.memory.kind == "module":
        core.memory = MemoryModule(
            stimulus_log=core.stimulus_log, memory_dir=home / "memory",
            model_providers=[_provider(spec.memory.model)] if spec.memory.model else [],
            embedding_providers=[_provider(spec.memory.embedding)] if spec.memory.embedding else [],
            max_input_chars=spec.memory.episode_max_chars,
        )
        if spec.memory.consolidate_every_seconds is not None:
            core.memory_consolidator = MemoryConsolidator(
                core.memory, every_seconds=spec.memory.consolidate_every_seconds,
                max_events=spec.memory.episode_max_events, max_chars=spec.memory.episode_max_chars,
                context_events=spec.memory.episode_context_events,
            )
    if core.memory is not None:
        recall = RecallTool(core.memory, budget_tokens=spec.memory.recall_budget_tokens)
        if spec.memory.recall_description is not None:
            recall.description = spec.memory.recall_description
        core.tools[recall.name] = recall
    if spec.interface.kind == "none":
        return AssembledAgent(core, None, spec)
    callback = core.wake if spec.core == "auto" else core.orient_and_wait
    if spec.interface.kind == "web":
        observer = WebChatUIObserver(stimulus_log=core.stimulus_log, orient_chat_message_callback=callback)
        mouth = WebChat(web_observer=observer)
    elif spec.interface.kind == "telegram":
        token = os.environ.get(spec.interface.bot_token_env)
        if not token:
            raise ValueError(
                f"Set {spec.interface.bot_token_env} to the Telegram bot token before boot"
            )
        journal = DeliveryJournal(home / "delivery.sqlite3")
        api = TelegramBotAPI(token)
        outbox = DurableOutbox(
            journal, TELEGRAM_TRANSPORT, TelegramSender(api, cwd=home),
            min_group_interval_seconds=spec.interface.outgoing_interval_seconds,
        )
        observer = TelegramObserver(
            stimulus_log=core.stimulus_log,
            orient_chat_message_callback=callback,
            api=api,
            inbox=DurableInbox(journal, TELEGRAM_TRANSPORT),
            outbox=outbox,
            allowed_user_ids=spec.interface.allowed_user_ids,
            allowed_chat_ids=spec.interface.allowed_chat_ids,
            poll_timeout_seconds=spec.interface.poll_timeout_seconds,
        )
        mouth = TelegramTool(
            outbox,
            allowed_chat_ids=spec.interface.allowed_chat_ids,
            allowed_user_ids=() if spec.interface.outgoing_chat_ids_only else spec.interface.allowed_user_ids,
        )
    else:
        observer = TerminalChatObserver(core.stimulus_log, callback)
        mouth = TerminalChat()
    core.tools[mouth.name] = mouth
    return AssembledAgent(core, observer, spec)


def render(spec: AgentSpec) -> str:
    spec.validate()
    return (
        GENERATED_HEADER + "from __future__ import annotations\n\n"
        "from pathlib import Path\n"
        "from theseus.assembly import AgentSpec, ModelSpec, MemorySpec, InterfaceSpec, PairingSpec, run_agent\n\n"
        f"SPEC = {pformat(spec, width=100)}\n\n"
        "if __name__ == '__main__':\n"
        "    run_agent(SPEC, Path(__file__).resolve().parent / 'state')\n"
    )


def _atomic_write(path: Path, content: str) -> None:
    temporary = None
    try:
        with tempfile.NamedTemporaryFile(mode="w", encoding="utf-8", dir=path.parent, delete=False) as stream:
            temporary = Path(stream.name)
            stream.write(content)
            stream.flush()
            os.fsync(stream.fileno())
        os.replace(temporary, path)
    finally:
        if temporary is not None:
            temporary.unlink(missing_ok=True)


def assemble(spec: AgentSpec, output: Path) -> Path:
    """Validate and atomically replace only our generated launcher; never boot it."""
    content = render(spec)
    compile(content, "agent.py", "exec")
    output = Path(output)
    output.mkdir(parents=True, exist_ok=True)
    destination = output / "agent.py"
    if destination.is_symlink() or (destination.exists() and (
        not destination.is_file() or not destination.read_text(encoding="utf-8").startswith(GENERATED_HEADER)
    )):
        raise ValueError(f"Refusing to replace non-assembler file: {destination}")
    _atomic_write(destination, content)
    return destination


def run_agent(spec: AgentSpec, default_home: Path) -> None:
    parser = argparse.ArgumentParser(description=f"Run {spec.name}")
    parser.add_argument("--home", type=Path, default=default_home)
    parser.add_argument(
        "--log-path", type=Path,
        help="Stimulus log location (default: <home>/stimulus_log.jsonl)",
    )
    parser.add_argument("--check", action="store_true", help="Validate without creating state or starting the agent")
    parser.add_argument("--preflight", action="store_true", help="Validate local state without external activity")
    parser.add_argument("--managed", action="store_true", help="Use the bounded deployment lifecycle")
    parser.add_argument("--deployment-id")
    parser.add_argument("--agent-id")
    parser.add_argument("--control-path", type=Path)
    parser.add_argument("--status-path", type=Path)
    parser.add_argument("--shutdown-timeout", type=float, default=30.0)
    args = parser.parse_args()
    logging.basicConfig(level=logging.INFO)
    spec.validate()
    if args.check:
        print(f"{spec.name}: configuration valid")
        return
    from theseus.deployment_store import runtime_lock

    with runtime_lock(args.home):
        agent = build_agent(spec, args.home, log_path=args.log_path)
        if args.preflight:
            print(json.dumps(agent.preflight(), sort_keys=True))
            return
        if not args.managed:
            agent.run()
            return
        missing = [
            name for name, value in (
                ("--deployment-id", args.deployment_id),
                ("--agent-id", args.agent_id),
                ("--control-path", args.control_path),
                ("--status-path", args.status_path),
            ) if value is None
        ]
        if missing:
            parser.error(f"--managed requires {', '.join(missing)}")

        previous = signal.getsignal(signal.SIGTERM)

        def request_shutdown(_signum, _frame) -> None:
            agent.request_shutdown()

        signal.signal(signal.SIGTERM, request_shutdown)
        try:
            clean = agent.run_managed(
                deployment_id=args.deployment_id,
                agent_id=args.agent_id,
                control_path=args.control_path,
                status_path=args.status_path,
                shutdown_timeout_seconds=args.shutdown_timeout,
            )
        finally:
            signal.signal(signal.SIGTERM, previous)
        if not clean:
            parser.exit(1, f"{spec.name}: shutdown deadline expired or drain failed\n")


def main() -> None:
    parser = argparse.ArgumentParser(description="Assemble a Theseus agent from a Python definition exporting SPEC")
    parser.add_argument("definition", type=Path)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--target", choices=("agent", "compose"), default="agent")
    args = parser.parse_args()
    try:
        definition = runpy.run_path(str(args.definition))
        if args.target == "compose":
            from theseus.deployment import DeploymentSpec
            from theseus.deployment_bundle import assemble_compose

            deployment = definition.get("DEPLOYMENT")
            if not isinstance(deployment, DeploymentSpec):
                raise ValueError("Compose definition must export DEPLOYMENT = DeploymentSpec(...)")
            print(assemble_compose(
                deployment, args.output, definition_root=args.definition.resolve().parent
            ))
        else:
            spec = definition.get("SPEC")
            if not isinstance(spec, AgentSpec):
                raise ValueError("Definition must export SPEC = AgentSpec(...)")
            print(assemble(spec, args.output))
    except (ValueError, TypeError, OSError, ImportError, AttributeError, SyntaxError) as exc:
        parser.exit(1, f"assemble: {exc}\n")


# Re-export the deployment vocabulary beside AgentSpec for definition authors.
from theseus.deployment import DeploymentSpec, ResourceSpec  # noqa: E402
