"""Small, repeatable agent composition; definitions are ordinary trusted Python."""
from __future__ import annotations

import argparse
import logging
import os
from pathlib import Path
from pprint import pformat
import runpy
import tempfile
import threading
from dataclasses import dataclass, field

from theseus.agentic_memory import AgenticMemory
from theseus.auto_core import Autocore
from theseus.cadence import Cadence
from theseus.chat_observer import TerminalChatObserver
from theseus.context_assembler import ContextAssembler
from theseus.memory_module import MemoryModule
from theseus.memory_store import MemoryStore
from theseus.model_providers import PROVIDER_REGISTRY
from theseus.ooda_core import OODACore
from theseus.stimulus_log import StimulusLog
from theseus.tools.recall import RecallTool
from theseus.tools.registry import all_tools
from theseus.tools.terminal_chat import TerminalChat
from theseus.tools.web_chat import WebChat
from theseus.web_chat_ui_observer import WebChatUIObserver

GENERATED_HEADER = "# Generated by Theseus Agent Assembler. Edit the definition and reassemble.\n"


@dataclass(frozen=True)
class ModelSpec:
    provider: str
    model: str
    context: int = 4096
    tick: int = 300
    during: str | None = None


@dataclass(frozen=True)
class MemorySpec:
    # Autocore holds either module; consolidation remains an explicit agent policy.
    kind: str = "none"
    model: ModelSpec | None = None
    embedding: ModelSpec | None = None
    recall_budget_tokens: int = 2000
    recall_description: str | None = None


@dataclass(frozen=True)
class InterfaceSpec:
    kind: str = "terminal"
    host: str = "127.0.0.1"
    port: int = 8000


@dataclass(frozen=True)
class AgentSpec:
    name: str
    constitution: str
    models: tuple[ModelSpec, ...]
    persona: str = ""
    core: str = "auto"
    tools: tuple[str, ...] = ()
    memory: MemorySpec = field(default_factory=MemorySpec)
    interface: InterfaceSpec = field(default_factory=InterfaceSpec)
    window_size: int = 200

    def validate(self) -> None:
        for label, value in (("name", self.name), ("constitution", self.constitution)):
            if not isinstance(value, str) or not value.strip():
                raise ValueError(f"{label} must be nonempty text")
        if not isinstance(self.persona, str):
            raise ValueError("persona must be text")
        if self.core not in ("auto", "ooda"):
            raise ValueError("core must be 'auto' or 'ooda'")
        if type(self.window_size) is not int or self.window_size <= 0:
            raise ValueError("window_size must be a positive integer")
        if not isinstance(self.models, tuple) or not self.models:
            raise ValueError("models must be a nonempty tuple of ModelSpec values")
        for model in self.models:
            _validate_model(model)
        if self.core == "auto":
            if sum(model.during is None for model in self.models) != 1:
                raise ValueError("auto requires exactly one default model (during=None)")
            cadence = Cadence.parse(self.cadence_text())
            if cadence.lint_lines() or len(cadence.rules) != len(self.models):
                raise ValueError(f"Invalid cadence: {self.cadence_text()}")
        elif any(model.during is not None for model in self.models):
            raise ValueError("OODA models are ordered fallbacks; during is only for auto")
        elif len({model.context for model in self.models}) != 1:
            raise ValueError("OODA fallback models must use the same context budget")
        if not isinstance(self.tools, tuple) or any(not isinstance(t, str) for t in self.tools):
            raise ValueError("tools must be a tuple of registered tool names")
        unknown = set(self.tools) - all_tools().keys()
        if unknown:
            raise ValueError(f"Unknown tools: {', '.join(sorted(unknown))}")
        if len(set(self.tools)) != len(self.tools):
            raise ValueError("Duplicate tool names")
        if not isinstance(self.interface, InterfaceSpec):
            raise ValueError("interface must be an InterfaceSpec")
        if self.interface.kind not in ("terminal", "web"):
            raise ValueError("interface must be 'terminal' or 'web'")
        if not isinstance(self.interface.host, str) or not self.interface.host.strip():
            raise ValueError("interface host must be nonempty text")
        if type(self.interface.port) is not int or not 1 <= self.interface.port <= 65535:
            raise ValueError("interface port must be between 1 and 65535")
        if not isinstance(self.memory, MemorySpec):
            raise ValueError("memory must be a MemorySpec")
        memory = self.memory
        if memory.kind not in ("none", "amem", "module"):
            raise ValueError("memory kind must be 'none', 'amem', or 'module'")
        if type(memory.recall_budget_tokens) is not int or memory.recall_budget_tokens <= 0:
            raise ValueError("recall_budget_tokens must be a positive integer")
        if memory.recall_description is not None and not isinstance(memory.recall_description, str):
            raise ValueError("recall_description must be text")
        if memory.kind == "amem":
            _validate_model(memory.model)
            _validate_model(memory.embedding)
        elif memory.kind == "module":
            if self.core != "auto":
                raise ValueError("MemoryModule requires auto; it does not implement OODA's form() lifecycle")
            for model in (memory.model, memory.embedding):
                if model is not None:
                    _validate_model(model)
        elif any(value is not None for value in (
            memory.model, memory.embedding, memory.recall_description
        )):
            raise ValueError("memory kind 'none' does not accept memory options")

    def cadence_text(self) -> str:
        return "# Cadence\n\n" + "".join(
            f"- {model.during or 'default'}: {model.provider} {model.model}, "
            f"context {model.context}, tick every {model.tick} seconds\n"
            for model in self.models
        )


def _validate_model(model: ModelSpec | None) -> None:
    if not isinstance(model, ModelSpec):
        raise ValueError("Expected a ModelSpec")
    if model.provider not in PROVIDER_REGISTRY:
        raise ValueError(f"Unknown provider {model.provider!r}; choose from {', '.join(PROVIDER_REGISTRY)}")
    if not isinstance(model.model, str) or not model.model or any(c.isspace() for c in model.model):
        raise ValueError("Model name must be a nonempty token without whitespace")
    for label, value in (("context", model.context), ("tick", model.tick)):
        if type(value) is not int or value <= 0:
            raise ValueError(f"Model {label} must be a positive integer")
    if model.during is not None and (not isinstance(model.during, str) or not model.during):
        raise ValueError("during must be a time window such as '08:00-22:00'")


def _provider(spec: ModelSpec):
    return PROVIDER_REGISTRY[spec.provider](model=spec.model)


@dataclass
class AssembledAgent:
    core: Autocore | OODACore
    observer: TerminalChatObserver | WebChatUIObserver
    spec: AgentSpec

    def run(self) -> None:
        if self.spec.core == "auto":
            threading.Thread(target=self.core.loop, name="agent-core", daemon=True).start()
        if self.spec.interface.kind == "web":
            self.observer.serve(host=self.spec.interface.host, port=self.spec.interface.port)
        else:
            while True:
                try:
                    self.observer.observe_chat_message()
                except EOFError:
                    break


def build_agent(spec: AgentSpec, home: Path) -> AssembledAgent:
    """Compose without starting loops, listeners, or making model requests.

    Identity and cadence are assembler-owned and reapplied on boot. Everything
    else in home is runtime-owned. Use a fresh home for an isolated test agent.
    """
    spec.validate()
    home = Path(home).resolve()
    # Construct OODA providers before touching the home (e.g. missing API keys).
    providers = [_provider(model) for model in spec.models] if spec.core == "ooda" else []
    home.mkdir(parents=True, exist_ok=True)
    for name, content in (("CONSTITUTION.md", spec.constitution),
                          ("PERSONA.md", spec.persona),
                          ("CADENCE.md", spec.cadence_text())):
        _atomic_write(home / name, content)
    tools = {name: tool for name, tool in all_tools(cwd=home).items() if name in spec.tools}
    if spec.core == "auto":
        core = Autocore(name=spec.name, home_directory=home, tools=tools)
        core.context_assembler.window_size = spec.window_size
    else:
        log = StimulusLog(home / "stimulus_log.jsonl")
        core = OODACore(
            name=spec.name, constitution=spec.constitution, persona=spec.persona,
            stimulus_log=log, tools=tools, model_providers=providers,
            context_assembler=ContextAssembler(
                log, window_size=spec.window_size, context_tokens=spec.models[0].context,
            ),
        )
    if spec.memory.kind == "amem":
        core.memory = AgenticMemory(
            model_providers=[_provider(spec.memory.model)],
            embedding_providers=[_provider(spec.memory.embedding)],
            store=MemoryStore(home / "a_mem.jsonl"), stimulus_log=core.stimulus_log,
        )
    elif spec.memory.kind == "module":
        core.memory = MemoryModule(
            stimulus_log=core.stimulus_log, memory_dir=home / "memory",
            model_providers=[_provider(spec.memory.model)] if spec.memory.model else [],
            embedding_providers=[_provider(spec.memory.embedding)] if spec.memory.embedding else [],
        )
    if core.memory is not None:
        recall = RecallTool(core.memory, budget_tokens=spec.memory.recall_budget_tokens)
        if spec.memory.recall_description is not None:
            recall.description = spec.memory.recall_description
        core.tools[recall.name] = recall
    callback = core.wake if spec.core == "auto" else core.orient_and_wait
    if spec.interface.kind == "web":
        observer = WebChatUIObserver(stimulus_log=core.stimulus_log, orient_chat_message_callback=callback)
        mouth = WebChat(web_observer=observer)
    else:
        observer = TerminalChatObserver(core.stimulus_log, callback)
        mouth = TerminalChat()
    core.tools[mouth.name] = mouth
    return AssembledAgent(core, observer, spec)


def render(spec: AgentSpec) -> str:
    spec.validate()
    return (
        GENERATED_HEADER + "from __future__ import annotations\n\n"
        "from pathlib import Path\n"
        "from theseus.assembly import AgentSpec, ModelSpec, MemorySpec, InterfaceSpec, run_agent\n\n"
        f"SPEC = {pformat(spec, width=100)}\n\n"
        "if __name__ == '__main__':\n"
        "    run_agent(SPEC, Path(__file__).resolve().parent / 'state')\n"
    )


def _atomic_write(path: Path, content: str) -> None:
    temporary = None
    try:
        with tempfile.NamedTemporaryFile(mode="w", encoding="utf-8", dir=path.parent, delete=False) as stream:
            temporary = Path(stream.name)
            stream.write(content)
            stream.flush()
            os.fsync(stream.fileno())
        os.replace(temporary, path)
    finally:
        if temporary is not None:
            temporary.unlink(missing_ok=True)


def assemble(spec: AgentSpec, output: Path) -> Path:
    """Validate and atomically replace only our generated launcher; never boot it."""
    content = render(spec)
    compile(content, "agent.py", "exec")
    output = Path(output)
    output.mkdir(parents=True, exist_ok=True)
    destination = output / "agent.py"
    if destination.is_symlink() or (destination.exists() and (
        not destination.is_file() or not destination.read_text(encoding="utf-8").startswith(GENERATED_HEADER)
    )):
        raise ValueError(f"Refusing to replace non-assembler file: {destination}")
    _atomic_write(destination, content)
    return destination


def run_agent(spec: AgentSpec, default_home: Path) -> None:
    parser = argparse.ArgumentParser(description=f"Run {spec.name}")
    parser.add_argument("--home", type=Path, default=default_home)
    parser.add_argument("--check", action="store_true", help="Validate without creating state or starting the agent")
    args = parser.parse_args()
    logging.basicConfig(level=logging.INFO)
    spec.validate()
    if args.check:
        print(f"{spec.name}: configuration valid")
        return
    build_agent(spec, args.home).run()


def main() -> None:
    parser = argparse.ArgumentParser(description="Assemble a Theseus agent from a Python definition exporting SPEC")
    parser.add_argument("definition", type=Path)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    try:
        spec = runpy.run_path(str(args.definition)).get("SPEC")
        if not isinstance(spec, AgentSpec):
            raise ValueError("Definition must export SPEC = AgentSpec(...)")
        print(assemble(spec, args.output))
    except (ValueError, TypeError, OSError, ImportError, AttributeError, SyntaxError) as exc:
        parser.exit(1, f"assemble: {exc}\n")
