"""Deterministic Docker Compose bundle generation for managed deployments."""
from __future__ import annotations

from dataclasses import asdict
import hashlib
import importlib.metadata
import json
import os
from pathlib import Path
import shutil
import subprocess
import tempfile
import tomllib
from typing import Any, Callable

from theseus.assembly import render
from theseus.deployment import DeploymentSpec, ResourceSpec


BUNDLE_HEADER = "# Generated by Theseus Compose Assembler. Reassemble instead of editing.\n"
MANIFEST = ".theseus-generated.json"
LOCK_FILE = "deployment.lock.json"
FORMAT_VERSION = 1
DEFAULT_BASE_IMAGE = "python:3.12-slim"
_REQUIRED_PROVIDER_SECRETS = {
    "openrouter": "OPENROUTER_API_KEY",
    "unsloth": "UNSLOTH_API_KEY",
}


def _json(data: Any) -> str:
    return json.dumps(data, indent=2, sort_keys=True, ensure_ascii=False) + "\n"


def _sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def _file_sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for block in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def _runtime_sha256(project_root: Path) -> str:
    """Identify the exact source and dependency inputs copied into the image."""
    digest = hashlib.sha256()
    roots = [project_root / "src" / "theseus"]
    roots.extend(
        path for name in ("pyproject.toml", "poetry.lock", "LICENSE", "README.md")
        if (path := project_root / name).exists()
    )
    files: list[Path] = []
    for root in roots:
        if root.is_dir():
            files.extend(path for path in root.rglob("*") if path.is_file())
        else:
            files.append(root)
    for path in sorted(
        (
            path for path in files
            if "__pycache__" not in path.parts and path.suffix not in (".pyc", ".pyo")
        ),
        key=lambda value: str(value.relative_to(project_root)),
    ):
        relative = str(path.relative_to(project_root)).encode("utf-8")
        digest.update(len(relative).to_bytes(4, "big"))
        digest.update(relative)
        content = path.read_bytes()
        digest.update(len(content).to_bytes(8, "big"))
        digest.update(content)
    return digest.hexdigest()


def _project_root() -> Path:
    root = Path(__file__).resolve().parents[2]
    required = (root / "pyproject.toml", root / "poetry.lock", root / "src" / "theseus")
    if not all(path.exists() for path in required):
        raise ValueError("Compose assembly requires a Theseus source checkout with poetry.lock")
    return root


def _theseus_identity(root: Path) -> tuple[str, str]:
    try:
        version = importlib.metadata.version("theseus")
    except importlib.metadata.PackageNotFoundError:
        with (root / "pyproject.toml").open("rb") as stream:
            version = tomllib.load(stream)["project"]["version"]
    result = subprocess.run(
        ["git", "rev-parse", "HEAD"], cwd=root, text=True, capture_output=True
    )
    commit = result.stdout.strip() if result.returncode == 0 else "unknown"
    return version, commit


def _required_secrets(spec: DeploymentSpec) -> set[str]:
    required: set[str] = set()
    for agent in spec.agents.values():
        if agent.interface.kind == "telegram":
            required.add(agent.interface.bot_token_env)
        models = list(agent.models)
        if agent.memory.model is not None:
            models.append(agent.memory.model)
        if agent.memory.embedding is not None:
            models.append(agent.memory.embedding)
        for model in models:
            secret = _REQUIRED_PROVIDER_SECRETS.get(model.provider)
            if secret is not None:
                required.add(secret)
    return required


def validate_managed_deployment(spec: DeploymentSpec, definition_root: Path) -> None:
    spec.validate()
    unsupported = [
        agent_id for agent_id, agent in spec.agents.items()
        if agent.core != "auto" or agent.interface.kind not in ("telegram", "none")
    ]
    if unsupported:
        raise ValueError(
            "managed Compose currently supports only Auto Telegram/headless agents: "
            + ", ".join(sorted(unsupported))
        )
    missing_secrets = _required_secrets(spec) - set(spec.secrets)
    if missing_secrets:
        raise ValueError(
            "deployment is missing required secret declarations: "
            + ", ".join(sorted(missing_secrets))
        )
    if any(
        model.provider == "claude"
        for agent in spec.agents.values()
        for model in (
            *agent.models,
            *((agent.memory.model,) if agent.memory.model is not None else ()),
            *((agent.memory.embedding,) if agent.memory.embedding is not None else ()),
        )
    ) and "claude" not in spec.installed_tools:
        raise ValueError("the claude provider requires a runtime image declaring the claude tool")
    definition_root = definition_root.resolve()
    for relative in spec.build_inputs:
        source = (definition_root / relative).resolve()
        if not source.is_relative_to(definition_root):
            raise ValueError(f"build input escapes the definition root: {relative}")
        if not source.is_file() or source.is_symlink():
            raise ValueError(f"build input is missing or not a regular file: {relative}")
        if source.name == ".env" or source.name.startswith(".env."):
            raise ValueError(f"environment files cannot be build inputs: {relative}")


def _requirements_lock(project_root: Path) -> str:
    with (project_root / "poetry.lock").open("rb") as stream:
        lock = tomllib.load(stream)
    packages: list[tuple[str, str, tuple[str, ...]]] = []
    for package in lock.get("package", []):
        if "main" not in package.get("groups", []):
            continue
        name = package["name"]
        version = package["version"]
        hashes = tuple(sorted({
            item["hash"] for item in package.get("files", [])
            if isinstance(item, dict) and isinstance(item.get("hash"), str)
        }))
        if not hashes:
            raise ValueError(f"dependency {name}=={version} has no immutable artifact hashes")
        packages.append((name, version, hashes))
    lines = [BUNDLE_HEADER.rstrip()]
    for name, version, hashes in sorted(packages, key=lambda item: item[0].casefold()):
        lines.append(f"{name}=={version} \\")
        for index, value in enumerate(hashes):
            suffix = " \\" if index < len(hashes) - 1 else ""
            lines.append(f"    --hash={value}{suffix}")
    return "\n".join(lines) + "\n"


def _copy_runtime(project_root: Path, staging: Path) -> None:
    runtime = staging / "runtime" / "theseus"
    (runtime / "src").mkdir(parents=True)
    shutil.copytree(
        project_root / "src" / "theseus",
        runtime / "src" / "theseus",
        ignore=shutil.ignore_patterns("__pycache__", "*.pyc", "*.pyo"),
    )
    for name in ("pyproject.toml", "LICENSE", "README.md", "poetry.lock"):
        source = project_root / name
        if source.exists():
            shutil.copy2(source, runtime / name)


def _entrypoint() -> str:
    return BUNDLE_HEADER + '''from __future__ import annotations

import os
from pathlib import Path
import sys


for name in filter(None, os.environ.get("THESEUS_SECRET_NAMES", "").split(",")):
    path = Path("/run/secrets") / name
    if not path.is_file():
        raise SystemExit(f"required secret file is missing: {name}")
    os.environ[name] = path.read_text(encoding="utf-8").rstrip("\\r\\n")

if len(sys.argv) < 2:
    raise SystemExit("agent command is required")
os.execvp(sys.argv[1], sys.argv[1:])
'''


def _dockerfile(spec: DeploymentSpec) -> str:
    tools = " ".join(spec.installed_tools)
    verify_tools = (
        "RUN set -eu; " + "; ".join(f"command -v {tool} >/dev/null" for tool in spec.installed_tools)
        if tools else ""
    )
    return BUNDLE_HEADER + f'''ARG BASE_IMAGE={spec.image or DEFAULT_BASE_IMAGE}
FROM ${{BASE_IMAGE}}
ARG THESEUS_UID={spec.uid}
ARG THESEUS_GID={spec.gid}
ARG THESEUS_WORKSPACE_GID={spec.workspace_gid}
RUN groupadd --gid ${{THESEUS_GID}} theseus \\
 && groupadd --gid ${{THESEUS_WORKSPACE_GID}} workspace \\
 && useradd --uid ${{THESEUS_UID}} --gid ${{THESEUS_GID}} --groups ${{THESEUS_WORKSPACE_GID}} --no-create-home theseus
COPY requirements.lock /build/requirements.lock
RUN python -m pip install --no-cache-dir --require-hashes --requirement /build/requirements.lock
COPY runtime/theseus /app/theseus
COPY agents /app/agents
COPY build-inputs /app/build-inputs
COPY entrypoint.py /app/entrypoint.py
ENV PYTHONPATH=/app/theseus/src:/app/build-inputs \\
    PYTHONDONTWRITEBYTECODE=1 \\
    PYTHONUNBUFFERED=1
{verify_tools}
USER ${{THESEUS_UID}}:${{THESEUS_GID}}
ENTRYPOINT ["python", "/app/entrypoint.py"]
'''


def _mount_lines(spec: DeploymentSpec, agent_id: str) -> list[str]:
    root = f"${{THESEUS_DEPLOYMENT_ROOT:-/srv/theseus/{spec.id}}}"
    lines = [
        f"{root}/data/agents/{agent_id}/state:/data/state",
        f"{root}/data/agents/{agent_id}/logs:/data/logs",
        f"{root}/control:/run/theseus-control:ro",
    ]
    peer_id = spec.peers.get(agent_id)
    if peer_id is not None:
        lines.append(f"{root}/data/agents/{peer_id}/logs:/peers/{peer_id}/logs:ro")
    lines.extend(
        f"{root}/data/workspaces/{workspace_id}:/workspaces/{workspace_id}"
        for workspace_id in spec.workspaces_for(agent_id)
    )
    return lines


def _compose(spec: DeploymentSpec, image_tag: str) -> str:
    lines = [BUNDLE_HEADER.rstrip(), "services:"]
    for agent_id in sorted(spec.agents):
        resource = spec.resources.get(agent_id, ResourceSpec())
        lines.extend([
            f"  {json.dumps(agent_id)}:",
            f"    image: {image_tag}",
            "    build:",
            "      context: .",
            "      args:",
            f"        BASE_IMAGE: {json.dumps(spec.image or DEFAULT_BASE_IMAGE)}",
            f"        THESEUS_UID: {spec.uid}",
            f"        THESEUS_GID: {spec.gid}",
            f"        THESEUS_WORKSPACE_GID: {spec.workspace_gid}",
            f"    platform: {spec.platform}",
            "    init: true",
            "    read_only: true",
            "    working_dir: /data/state",
            f"    user: {json.dumps(f'{spec.uid}:{spec.gid}')}",
            "    group_add:",
            f"      - {json.dumps(str(spec.workspace_gid))}",
            f"    cpus: {json.dumps(str(resource.cpus))}",
            f"    mem_limit: {json.dumps(f'{resource.memory_mb}m')}",
            "    security_opt:",
            "      - no-new-privileges:true",
            "    cap_drop:",
            "      - ALL",
            "    tmpfs:",
            "      - /tmp:rw,noexec,nosuid,size=256m",
            "    environment:",
            f"      THESEUS_SECRET_NAMES: {json.dumps(','.join(spec.secrets))}",
            "    command:",
            "      - python",
            f"      - /app/agents/{agent_id}/agent.py",
            "      - --home",
            "      - /data/state",
            "      - --log-path",
            "      - /data/logs/stimulus_log.jsonl",
            "    volumes:",
        ])
        lines.extend(f"      - {json.dumps(mount)}" for mount in _mount_lines(spec, agent_id))
        if spec.secrets:
            lines.append("    secrets:")
            lines.extend(f"      - {json.dumps(secret)}" for secret in spec.secrets)
    if spec.secrets:
        root = f"${{THESEUS_DEPLOYMENT_ROOT:-/srv/theseus/{spec.id}}}"
        lines.append("secrets:")
        for secret in sorted(spec.secrets):
            lines.extend([
                f"  {json.dumps(secret)}:",
                f"    file: {json.dumps(f'{root}/secrets/{secret}')}",
            ])
    return "\n".join(lines) + "\n"


def _deployment_data(
    spec: DeploymentSpec, definition_root: Path, project_root: Path
) -> dict[str, Any]:
    version, commit = _theseus_identity(project_root)
    inputs = []
    for relative in sorted(spec.build_inputs):
        source = (definition_root / relative).resolve()
        inputs.append({"path": relative, "sha256": _file_sha256(source)})
    agents = {}
    for agent_id in sorted(spec.agents):
        resolved = spec.resolved_agent(agent_id)
        agents[agent_id] = {
            "spec": asdict(resolved),
            "resources": asdict(spec.resources.get(agent_id, ResourceSpec())),
            "workspaces": list(spec.workspaces_for(agent_id)),
            "peer": spec.peers.get(agent_id),
            "mounts": _mount_lines(spec, agent_id),
        }
    return {
        "_generated_by": "theseus-compose-assembler",
        "format_version": FORMAT_VERSION,
        "deployment_id": spec.id,
        "platform": spec.platform,
        "runtime": spec.runtime,
        "base_image": spec.image or DEFAULT_BASE_IMAGE,
        "installed_tools": list(spec.installed_tools),
        "uid": spec.uid,
        "gid": spec.gid,
        "workspace_gid": spec.workspace_gid,
        "required_secrets": list(sorted(spec.secrets)),
        "build_inputs": inputs,
        "theseus": {
            "version": version,
            "commit": commit,
            "source_sha256": _runtime_sha256(project_root),
        },
        "agents": agents,
    }


def _write(path: Path, content: str | bytes) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if isinstance(content, str):
        content = content.encode("utf-8")
    path.write_bytes(content)


def _generated_files(root: Path) -> dict[str, str]:
    return {
        str(path.relative_to(root)): _file_sha256(path)
        for path in sorted(root.rglob("*"))
        if path.is_file() and path.name != MANIFEST
    }


def _validate_previous_output(output: Path) -> dict[str, str]:
    if not output.exists():
        return {}
    manifest_path = output / MANIFEST
    if manifest_path.is_symlink():
        raise ValueError(f"Refusing to replace symlinked manifest: {manifest_path}")
    if not manifest_path.is_file():
        if any(output.iterdir()):
            raise ValueError(f"Refusing to replace unowned bundle: {output}")
        return {}
    symlinks = [path for path in output.rglob("*") if path.is_symlink()]
    if symlinks:
        raise ValueError(f"Refusing to publish through bundle symlink: {symlinks[0]}")
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    if manifest.get("_generated_by") != "theseus-compose-assembler":
        raise ValueError(f"Refusing to replace unowned manifest: {manifest_path}")
    files = manifest.get("files")
    if not isinstance(files, dict):
        raise ValueError(f"Invalid generated manifest: {manifest_path}")
    for relative, expected_hash in files.items():
        path = output / relative
        if not path.is_file() or path.is_symlink() or _file_sha256(path) != expected_hash:
            raise ValueError(f"Refusing to replace modified generated file: {path}")
    return files


def _publish(staging: Path, output: Path) -> None:
    previous = _validate_previous_output(output)
    if not output.exists():
        os.replace(staging, output)
        return
    generated = _generated_files(staging)
    lock_path = output / LOCK_FILE
    remove_lock = False
    if lock_path.exists():
        if not lock_path.is_file() or lock_path.is_symlink():
            raise ValueError(f"Refusing to replace user-owned lock: {lock_path}")
        lock = json.loads(lock_path.read_text(encoding="utf-8"))
        if lock.get("_generated_by") != "theseus-compose-builder":
            raise ValueError(f"Refusing to replace user-owned lock: {lock_path}")
        remove_lock = True
    for relative in generated:
        destination = output / relative
        if destination.exists() and relative not in previous:
            raise ValueError(f"Refusing to replace user-owned file: {destination}")
    if remove_lock:
        lock_path.unlink()
    for relative in previous.keys() - generated.keys():
        (output / relative).unlink()
    for source in sorted(staging.rglob("*")):
        relative = source.relative_to(staging)
        destination = output / relative
        if source.is_dir():
            destination.mkdir(parents=True, exist_ok=True)
        else:
            destination.parent.mkdir(parents=True, exist_ok=True)
            os.replace(source, destination)
    shutil.rmtree(staging)


def assemble_compose(
    spec: DeploymentSpec, output: Path, *, definition_root: Path
) -> Path:
    """Stage, validate, and publish a complete managed deployment bundle."""
    output = Path(output)
    if output.is_symlink():
        raise ValueError(f"Refusing to replace symlinked bundle: {output}")
    output = output.resolve()
    definition_root = Path(definition_root).resolve()
    validate_managed_deployment(spec, definition_root)
    project_root = _project_root()
    output.parent.mkdir(parents=True, exist_ok=True)
    staging = Path(tempfile.mkdtemp(prefix=f".{output.name}-staging-", dir=output.parent))
    try:
        data = _deployment_data(spec, definition_root, project_root)
        canonical = _json(data).encode("utf-8")
        spec_hash = _sha256(canonical)
        image_tag = f"theseus-{spec.id}:{spec_hash[:12]}"
        data["resolved_spec_sha256"] = spec_hash
        data["image_tag"] = image_tag
        _write(staging / "deployment.json", _json(data))
        _write(staging / "compose.yaml", _compose(spec, image_tag))
        _write(staging / "Dockerfile", _dockerfile(spec))
        _write(staging / "entrypoint.py", _entrypoint())
        _write(staging / "requirements.lock", _requirements_lock(project_root))
        _write(staging / ".dockerignore", BUNDLE_HEADER + "*\n!Dockerfile\n!requirements.lock\n!entrypoint.py\n!agents/**\n!runtime/**\n!build-inputs/**\n")
        _write(
            staging / "secrets.example",
            BUNDLE_HEADER + "".join(
                f"# provision {name} as a file named {name}\n" for name in sorted(spec.secrets)
            ),
        )
        _write(
            staging / "README.md",
            BUNDLE_HEADER
            + f"# {spec.id}\n\n"
              "Generated managed deployment. Do not put credentials or state in this bundle.\n\n"
              "1. Run `python -m theseus.build_deployment .`.\n"
              f"2. Provision `/srv/theseus/{spec.id}` with `DeploymentPaths.prepare()` and `apply_ownership()`.\n"
              "3. Write each required secret value to the correspondingly named file under `secrets/`.\n"
              "4. Set `THESEUS_DEPLOYMENT_ROOT` if the host root differs, then run `docker compose up -d`.\n\n"
              "State, logs, shared workspaces, control files, snapshots, and secrets remain outside this release.\n",
        )
        for agent_id in sorted(spec.agents):
            launcher = render(spec.resolved_agent(agent_id))
            compile(launcher, f"agents/{agent_id}/agent.py", "exec")
            _write(staging / "agents" / agent_id / "agent.py", launcher)
        (staging / "build-inputs").mkdir()
        _write(staging / "build-inputs" / ".keep", BUNDLE_HEADER)
        for relative in sorted(spec.build_inputs):
            destination = staging / "build-inputs" / relative
            destination.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(definition_root / relative, destination)
        _copy_runtime(project_root, staging)
        files = _generated_files(staging)
        _write(staging / MANIFEST, _json({
            "_generated_by": "theseus-compose-assembler", "files": files,
        }))
        json.loads((staging / "deployment.json").read_text(encoding="utf-8"))
        _publish(staging, output)
    finally:
        if staging.exists():
            shutil.rmtree(staging)
    return output


def build_bundle(
    bundle: Path,
    *,
    run: Callable[..., subprocess.CompletedProcess[str]] = subprocess.run,
) -> Path:
    """Build without starting services and record immutable release identities."""
    bundle = Path(bundle)
    if bundle.is_symlink():
        raise ValueError(f"Refusing to build a symlinked bundle: {bundle}")
    bundle = bundle.resolve()
    data = json.loads((bundle / "deployment.json").read_text(encoding="utf-8"))
    if data.get("_generated_by") != "theseus-compose-assembler":
        raise ValueError("deployment.json is not an assembler-owned deployment")
    manifest = _validate_previous_output(bundle)
    for relative, expected in manifest.items():
        if relative == LOCK_FILE:
            continue
        if _file_sha256(bundle / relative) != expected:
            raise ValueError(f"bundle changed after assembly: {relative}")
    run(
        ["docker", "pull", "--platform", data["platform"], data["base_image"]],
        check=True, text=True, capture_output=True,
    )
    command = [
        "docker", "build", "--platform", data["platform"],
        "--build-arg", f"BASE_IMAGE={data['base_image']}",
        "--tag", data["image_tag"], str(bundle),
    ]
    run(command, check=True, text=True, capture_output=True)

    def inspect(reference: str) -> dict[str, Any]:
        result = run(
            ["docker", "image", "inspect", reference],
            check=True, text=True, capture_output=True,
        )
        value = json.loads(result.stdout)
        if not isinstance(value, list) or len(value) != 1:
            raise ValueError(f"Docker returned no unique identity for {reference}")
        return value[0]

    image = inspect(data["image_tag"])
    base = inspect(data["base_image"])
    configured_user = (image.get("Config") or {}).get("User")
    expected_user = f"{data['uid']}:{data['gid']}"
    if configured_user != expected_user:
        raise ValueError(
            f"built image user is {configured_user!r}; expected stable non-root {expected_user!r}"
        )
    lock = {
        "_generated_by": "theseus-compose-builder",
        "format_version": FORMAT_VERSION,
        "deployment_id": data["deployment_id"],
        "resolved_spec_sha256": data["resolved_spec_sha256"],
        "theseus": data["theseus"],
        "platform": data["platform"],
        "base_image": {
            "reference": data["base_image"],
            "content_id": base["Id"],
            "repo_digests": sorted(base.get("RepoDigests") or []),
            "os": base.get("Os"),
            "architecture": base.get("Architecture"),
        },
        "images": [{
            "tag": data["image_tag"],
            "content_id": image["Id"],
            "repo_digests": sorted(image.get("RepoDigests") or []),
            "platform": data["platform"],
            "os": image.get("Os"),
            "architecture": image.get("Architecture"),
            "user": configured_user,
        }],
        "build_inputs": data["build_inputs"],
        "image_exports": [{
            "reference": image["Id"],
            "platform": data["platform"],
            "suggested_archive": f"{data['deployment_id']}-{image['Id'].removeprefix('sha256:')}.tar",
        }],
    }
    lock_path = bundle / LOCK_FILE
    if lock_path.exists():
        current = json.loads(lock_path.read_text(encoding="utf-8"))
        if current.get("_generated_by") != "theseus-compose-builder":
            raise ValueError(f"Refusing to replace user-owned lock: {lock_path}")
    temporary = bundle / f".{LOCK_FILE}.tmp"
    temporary.write_text(_json(lock), encoding="utf-8")
    os.replace(temporary, lock_path)
    return lock_path
